#definimos el nombre del workflow
name: prueba1

#definimos el evento disparador de este wf
# documentacion: https://docs.github.com/es/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master


#definimos jobs y steps

jobs:
  primer_job:
    runs-on: ubuntu-latest #definir sistma operativo del servidor que realizara las acciones, este debe definirse en cada uno de los jobs
    steps:
      - name: Imprimir hola mundo
        run: echo "hola mundo, este es mi primer step"

      - name: touch
        run: touch archivo.txt

      - name: set text
        run: echo "hola mundo, archivo txt" >> archivo.txt

      - name: read text
        run: cat archivo.txt

  other:
    runs-on: ubuntu-latest
    needs: [primer_job]  #definimos dependencia, necesita que primero se ejecute el job primer_job antes de ejecutar other
    steps:
      - name: LS
        run: ls -al