#definimos el nombre del workflow
name: prueba1

#definimos el evento disparador de este wf
on: [push]

#definimos jobs y steps

jobs:
  primer_job:
    runs-on: ubuntu-latest #definir sistma operativo del servidor que realizara las acciones, este debe definirse en cada uno de los jobs
    steps:
      - name: Imprimir hola mundo
        run: echo "hola mundo, este es mi primer step"

  other:
    runs-on: ubuntu-latest
    steps:
      - name: LS
        run: ls -al